buildscript {
    repositories {
        // These repositories are only for Gradle plugins, put any other repositories in the repository block further below
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
    id 'com.radimous.vh-addon-dev' version '0.3.6'
    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}

apply plugin: 'org.spongepowered.mixin'


group = mod_group_id
version = mod_version

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

publishMods {
    file = jar.archiveFile
    changelog = file("CHANGELOG.md").text
    type = STABLE
    modLoaders.add("forge")
    curseforge {
        projectId = "1098054"
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        minecraftVersions.add("1.18.2")
        requires("vault-hunters-official-mod")
        optional("wolds-vaults-official-mod")
        clientRequired = true
        serverRequired = false
        javaVersions.add(JavaVersion.VERSION_17)
    }
}

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true
    runs {
        configureEach {
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }
        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            workingDirectory project.file('run-data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"

    config "${mod_id}.mixins.json"
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
     flatDir {
         dir 'libs'
     }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {

    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    //VH
    implementation fg.deobf("curse.maven:vault-hunters-official-mod-458203:${vault_hunters_version}")

    //deps
    implementation fg.deobf("curse.maven:curios-309927:4418032")
    implementation fg.deobf("curse.maven:sophisticated-backpacks-vault-hunters-edition-696425:4287544")
    implementation fg.deobf("curse.maven:autoreglib-250363:3642382")
    implementation fg.deobf("curse.maven:quark-243121:3840125")
    implementation fg.deobf("curse.maven:architects-palette-433862:4498424")
    implementation fg.deobf("curse.maven:geckolib-388172:4181370")
    implementation fg.deobf("curse.maven:cofh-core-69162:4801048") // wold plushie effects
    implementation fg.deobf("curse.maven:alexs-mobs-426558:3853078")
    implementation fg.deobf("curse.maven:citadel-331936:3783096") // alex mobs dep

    implementation fg.deobf("curse.maven:create-328085:4550986") // config

    //faster loading
    implementation fg.deobf("curse.maven:lazy-dfu-forge-460819:3544496")
    implementation fg.deobf("curse.maven:modernfix-790626:4565795")

    //qol mods
    implementation fg.deobf("curse.maven:configured-457570:4462832")
    implementation fg.deobf("curse.maven:jei-238222:4351311")


    implementation fg.deobf("curse.maven:sophisticated-core-618298:5296312")
    implementation fg.deobf("curse.maven:sophisticated-backpacks-422301:5654080")
    implementation fg.deobf("curse.maven:sophisticated-storage-619320:5809745")

    compileOnly fg.deobf("local:wolds-vaults-official-mod-vhcir-stub:0.32.0")
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version       : forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id              : mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors         : mod_authors, mod_description: mod_description,
            issue_tracker_url   : issue_tracker_url
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

// Example for how to get properties into the manifest for reading at runtime.
tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                "Specification-Title"     : mod_id,
                "Specification-Vendor"    : mod_authors,
                "Specification-Version"   : "1", // We are version 1 of ourselves
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : mod_authors,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }

    // This is the preferred method to reobfuscate your jar file
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}
